### PR TITLE
Chaining arrow syntax fix introduces trailing whitespaces

### LINKED ISSUE #695: Chaining arrow syntax fix introduces trailing whitespaces
Steps to reproduce:

`git clone https://github.com/biemond/biemond-wildfly.git` 
`git checkout 'v1.2.7'` 

```
rake lint
manifests/datasources/datasource.pp - WARNING: arrow should be on the right operand's line on line 14
manifests/datasources/xa_datasource.pp - WARNING: arrow should be on the right operand's line on line 15
manifests/deployment.pp - WARNING: arrow should be on the right operand's line on line 29
manifests/init.pp - WARNING: arrow should be on the right operand's line on line 55
manifests/init.pp - WARNING: arrow should be on the right operand's line on line 56
manifests/init.pp - WARNING: arrow should be on the right operand's line on line 57
manifests/install.pp - WARNING: arrow should be on the right operand's line on line 24
manifests/modcluster/config.pp - WARNING: arrow should be on the right operand's line on line 33
manifests/modcluster/config.pp - WARNING: arrow should be on the right operand's line on line 38
manifests/patch/online.pp - WARNING: arrow should be on the right operand's line on line 15
manifests/security/domain.pp - WARNING: arrow should be on the right operand's line on line 31
manifests/security/domain.pp - WARNING: arrow should be on the right operand's line on line 39
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 167
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 172
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 179
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 187
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 200
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 239
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 254
manifests/security/ldap_realm.pp - WARNING: arrow should be on the right operand's line on line 273
manifests/service.pp - WARNING: arrow should be on the right operand's line on line 37
manifests/undertow/https.pp - WARNING: arrow should be on the right operand's line on line 36
manifests/undertow/https.pp - WARNING: arrow should be on the right operand's line on line 46
```

And after `puppet-lint --fix manifests` I got

```
manifests/datasources/datasource.pp - ERROR: trailing whitespace found on line 14
manifests/datasources/xa_datasource.pp - ERROR: trailing whitespace found on line 15
manifests/deployment.pp - ERROR: trailing whitespace found on line 29
manifests/install.pp - ERROR: trailing whitespace found on line 24
manifests/modcluster/config.pp - ERROR: trailing whitespace found on line 33
manifests/modcluster/config.pp - ERROR: trailing whitespace found on line 38
manifests/patch/online.pp - ERROR: trailing whitespace found on line 15
manifests/service.pp - ERROR: trailing whitespace found on line 37
manifests/undertow/https.pp - ERROR: trailing whitespace found on line 36
manifests/undertow/https.pp - ERROR: trailing whitespace found on line 46
```

### PR DESCRIPTION
**Pull request by rnelson0**
Build the proper chain of tokens for the appropriate placement of the arrow chain, indents, and linefeeds

Fixes #695

#puppethack

### CODE REVIEW

File: spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb [hunk 1]
```diff
@@ -11,7 +11,8 @@
 
       context 'arrow on the line of left operand' do
         let(:code) do
-          "Package['httpd']  #{operator}
+          "
+            Package['httpd']  #{operator}
```
Comment (james-stocks) [inline spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb]: I would be curious whether the previous version of this spec still work? i.e. does your code also work OK when there is NOT a newline or whitespace to process?
Perhaps it would be good to leave this spec unchanged, and add an additional spec that describes itself as being 'arrow on the line of left operand, with whitespacing'

Comment (rnelson0) [inline spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb]: That's a good question, 10.4 doesn't say how it should be aligned. @jbondpdx any thoughts?

Comment (james-stocks) [inline spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb]: To clarify - I think that both the previous version and the current version of this test could be kept. Because your changes includes handling of optional newline and whitespace tokens; it may be valuable to test both that:

a. arrow_on_right_operand_line.rb's code works when line and space characters appear
b. arrow_on_right_operand_line.rb's code does not error when there are no line or space tokens

Comment (jbondpdx) [inline spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb]: First of all, I'm _very_ sorry this slipped by me for so long. That said, I don't have any strong opinions on the alignment. It could be something we want to add to Style Guide, but I'd likely be asking @rnelson0 , David Schmitt, Henrik, and/or Hunter for opinions on it.

**Comment by rodjek** [comment]
Rebased to clear up merge conflicts

**Comment by rnelson0** [comment]
@rodjek thanks for fixing that, sorry that it slipped past me. Are there any other concerns before merging this?

**Comment by rodjek** [comment]
@rnelson0 no worries, the conflicts were mostly my fault anyway (shoutout to mass rubocop changes)
