### PR TITLE
Handle unicode spaces in the tokeniser

### LINKED ISSUE #732: NoMethodError: undefined method `type' for nil:NilClass
puppet-lint version: 2.3.0
ruby version: 2.3.1-p112
platform: x86_64-darwin15
file path: server-lint-test.pp
file contents:
```
# Class: sys11icinga2::server
class sys11icinga2::server (
) {
  ##
  ## Install the nagios-nrpe-plugin
  ##
  package { 'nagios-nrpe-plugin':
    ensure => 'installed',
  }
}

```
error:
```
NoMethodError: undefined method `type' for nil:NilClass
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-trailing_newline-check-1.1.0/lib/puppet-lint/plugins/check_trailing_newline.rb:5:in `check'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checkplugin.rb:21:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:58:in `block in run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `each'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/checks.rb:56:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint.rb:191:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:61:in `block in run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `each'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/lib/puppet-lint/bin.rb:58:in `run'
/Users/mbaur/.rvm/gems/ruby-2.3.1/gems/puppet-lint-2.3.0/bin/puppet-lint:7:in `<top (required)>'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/puppet-lint:23:in `load'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/puppet-lint:23:in `<main>'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/mbaur/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

### PR DESCRIPTION
**Pull request by rodjek**
Fixes #732

### CODE REVIEW

File: lib/puppet-lint/lexer.rb [hunk 1]
```diff
@@ -258,7 +260,7 @@ def tokenise(code)
               length += str_contents.size
             end
 
-          elsif whitespace = chunk[/\A([ \t]+)/, 1]
+          elsif whitespace = chunk[/\A([\t\v\f\p{Zs}]+)/, 1]
```
Comment (rnelson0) [inline lib/puppet-lint/lexer.rb]: Would you mind adding a comment describing the regex classes used here?

Comment (rodjek) [inline lib/puppet-lint/lexer.rb]: Sure
